apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ybrainy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: ybrainy-api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
          env:
            - name: YBRAINY_EUREKA_URL
              value: http://eureka:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: ybrainy
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8088
      targetPort: 8088

