apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ybrainy
resources:
  - ../../../../event-service/k8s/configmap.yaml
  - ../../../../event-service/k8s/deployment.yaml
  - ../../../../event-service/k8s/service.yaml
  - ../../../../feedback-service/k8s/configmap.yaml
  - ../../../../feedback-service/k8s/deployment.yaml
  - ../../../../feedback-service/k8s/service.yaml
  - ../../../../inscription-service/k8s/configmap.yaml
  - ../../../../inscription-service/k8s/deployment.yaml
  - ../../../../inscription-service/k8s/service.yaml
