apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollment-service
  namespace: ybrainy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrollment-service
  template:
    metadata:
      labels:
        app: enrollment-service
    spec:
      containers:
        - name: enrollment-service
          image: ybrainy/enrollment-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
          env:
            - name: SERVER_PORT
              value: "8085"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/ybrainy_enrollments?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: enrollment-service
  namespace: ybrainy
spec:
  selector:
    app: enrollment-service
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP
