global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: cart-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["cart-service:8954"]

  - job_name: payment-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["payment-service:8095"]

  - job_name: finance-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["finance-service:8995"]

