spring.application.name=YBrainy_MEvents

server.servlet.context-path=/YBrainy_EM
Server.port = 8089

# DB Configuration :
spring.datasource.url=jdbc:mysql://localhost:3306/YBrainy?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# JPA Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#eureka registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true