# Shared config for ALL microservices
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# RabbitMQ shared config
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Eureka shared config
eureka.client.service-url.defaultZone=${YBRAINY_EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
