apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ybrainy-events
  namespace: flux-system
spec:
  interval: 1m
  timeout: 5m0s
  ref:
    branch: integration-final
  url: https://github.com/issamrh/ESPRIT-PI-4SAE4-2025-2026-Ybrainy.git
