apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: event-service
  namespace: flux-system
spec:
  image: hos77/event-service
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: feedback-service
  namespace: flux-system
spec:
  image: hos77/feedback-service
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: inscription-service
  namespace: flux-system
spec:
  image: hos77/inscription-service
  interval: 5m
