apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: event-service
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: event-service
  filterTags:
    pattern: '^[0-9]+$'
    extract: '$0'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: feedback-service
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: feedback-service
  filterTags:
    pattern: '^[0-9]+$'
    extract: '$0'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: inscription-service
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: inscription-service
  filterTags:
    pattern: '^[0-9]+$'
    extract: '$0'
  policy:
    numerical:
      order: asc
