apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-service
  namespace: ybrainy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-service
  template:
    metadata:
      labels:
        app: quiz-service
    spec:
      containers:
        - name: quiz-service
          image: ybrainy/quiz-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: SERVER_PORT
              value: "8083"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/ybrainy_quiz?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-service
  namespace: ybrainy
spec:
  selector:
    app: quiz-service
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30083
  type: NodePort
