server.port=8761
spring.application.name=eureka-server

# These 2 lines fix the 404 Whitelabel Dashboard issue:
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.prefer-file-system-access=false

# Standalone setup
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:8761

eureka.instance.hostname=localhost