server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forum_threads?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 5000
    listener:
      simple:
        missing-queues-fatal: false
        retry:
          enabled: true
          initial-interval: 5000
          max-attempts: 3
          multiplier: 2.0
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 105MB

ai:
  api-key: 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
  model: llama-3.1-8b-instant
  api-base-url: https://api.groq.com/openai/v1/chat/completions

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
