server:
  port: 8081

spring:
  application:
    name: partnership-service
  datasource:
    url: ${PARTNERSHIP_DB_URL:jdbc:mysql://127.0.0.1:3306/partnershipdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${PARTNERSHIP_DB_USERNAME:root}
    password: ${PARTNERSHIP_DB_PASSWORD:}  # vide si root n’a pas de mot de passe
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8770/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
