spring.datasource.url=jdbc:mysql://localhost:3306/gestion_forum?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8040
spring.application.name=forum-management


spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=105MB


management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


ai.api-key=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
ai.model=llama-3.1-8b-instant
ai.api-base-url=https://api.groq.com/openai/v1/chat/completions