apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: git://172.22.108.68:9418/ml-k8s.git
    targetRevision: master
    path: DEVOPS/ml-service/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ybrainy
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
