server:
  port: ${FORUM_CATEGORY_PORT:8082}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forum_categories?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: ${YBRAINY_EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: false
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info
