server:
  port: 8093

spring:
  application:
    name: scraper-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

scraper:
  python-command: python
  script-path: elearning_scraper.py
  working-directory: ${user.dir}
