apiVersion: v1
kind: ConfigMap
metadata:
  name: event-service-config
data:
  SERVER_PORT: "9001"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.devops.svc.cluster.local:3306/event_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC"
  YBRAINY_EUREKA_URL: "http://eureka-service.devops.svc.cluster.local:8761/eureka/"
  SPRING_RABBITMQ_HOST: "rabbitmq.devops.svc.cluster.local"
  ZIPKIN_URL: "http://zipkin.devops.svc.cluster.local:9411"
